# NumPy是Python数值计算最重要的基础包。
- ndarray，一个具有矢量算术运算和复杂广播能力的快速且节省空间的多维数组。
- 用于对整组数据进行快速运算的标准数学函数（无需编写循环）。
- 线性代数、随机数生成以及傅里叶变换功能。
- 用于集成由C、C++、Fortran等语言编写的代码的A C API。

In [1]:
import numpy as np

In [2]:
my_arr = np.arange(1000000)

In [3]:
my_list = list(range(1000000))

In [4]:
%time for _ in range(10): my_arr2 = my_arr * 2

CPU times: user 17.6 ms, sys: 12.5 ms, total: 30.1 ms
Wall time: 26.8 ms


In [5]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 259 ms, sys: 54 ms, total: 313 ms
Wall time: 311 ms


## 创建ndarray

In [12]:
np.array([6, 7.5, 8, 0, 1])

array([6. , 7.5, 8. , 0. , 1. ])

In [16]:
arr2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [20]:
print(arr2.ndim)
print(arr2.shape)
print(arr2.dtype)

2
(2, 4)
int64


In [21]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [23]:
np.zeros_like(arr2)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [24]:
np.empty((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [31]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [28]:
# 转换为ndarray 如果是就不复制
np.asarray(arr)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [29]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [32]:
np.full((2,2), 10)

array([[10, 10],
       [10, 10]])

In [33]:
np.full_like(arr, 10)

array([[10, 10, 10, 10],
       [10, 10, 10, 10]])

In [36]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [37]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## ndarray的数据类型
- int8 unint8  i1 u1
- int16 uint16 i2 u2
- int32 uint32 i4 u4
- int64 uint64 i8 u8
- float16 f2
- float32 f4或f
- float64 f8或d
- float128 f16 g
- complex64 complex128  c8 c16
- complex256 c32
- bool ?
- object O
- string_ S
- unicode U

In [40]:
arr = np.array([1,2], dtype = np.int32)
arr

array([1, 2], dtype=int32)

In [41]:
np.empty((2,2), dtype='?')

array([[ True, False],
       [False, False]])

In [42]:
np.arange(10).astype(float)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [44]:
np.arange(10).astype(arr.dtype)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

## NumPy数组的运算

In [48]:
arr = np.arange(6).reshape((2,3)).astype('f4')

In [49]:
arr * arr

array([[ 0.,  1.,  4.],
       [ 9., 16., 25.]], dtype=float32)

In [50]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [51]:
1 / arr

/var/folders/zh/jr5yvp7959jg1h14fjf34k800000gn/T/ipykernel_96566/1528351372.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([[       inf, 1.        , 0.5       ],
       [0.33333334, 0.25      , 0.2       ]], dtype=float32)

In [52]:
arr ** 0.5

array([[0.       , 1.       , 1.4142135],
       [1.7320508, 2.       , 2.236068 ]], dtype=float32)

In [53]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [55]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

## 基本的索引和切片

In [56]:
arr = np.arange(10)

In [57]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
arr[5]

5

In [59]:
arr[5:8]

array([5, 6, 7])

In [62]:
# 数据不会被复制
arr[5:8] = 12

In [63]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [64]:
arr[:] = 10

In [65]:
arr

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [66]:
arr2d = np.arange(9).reshape(3, -1)

In [67]:
arr2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [68]:
arr2d[2]

array([6, 7, 8])

In [69]:
arr2d[0][2]

2

In [70]:
arr2d[0,2]

2

In [71]:
arr3d = np.arange(12).reshape((2,2,3))

In [72]:
arr3d

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [73]:
arr3d[0]

array([[0, 1, 2],
       [3, 4, 5]])

In [76]:
arr3d[0,1]

array([3, 4, 5])

# 切片索引