In [1]:
import numpy as np

# 第04章 NumPy基础：数组和矢量计算

## 4.1 NumPy的ndarray：一种多维数组对象

### 创建ndarray

In [2]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [3]:
np.zeros(3), np.zeros((2,3))

(array([0., 0., 0.]),
 array([[0., 0., 0.],
        [0., 0., 0.]]))

### ndarray的数据类型

### NumPy数组的运算

### 基本的索引和切片
索引降维，切片不降维

In [4]:
# 列表 切片是新内存
a = list(range(10))
b = a[5:8]
b[:] = [10, 10, 10]
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
# 向量
arr = np.arange(10)
arr, arr[5], arr[5:8] # 索引 切片

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), 5, array([5, 6, 7]))

In [6]:
# 切片是视图 影响原对象
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [7]:
# 矩阵
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d, arr2d.shape

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 (3, 3))

In [8]:
arr2d[0][2], arr2d[0,2] # 索引

(3, 3)

In [9]:
arr2d[0,:2] # 切片

array([1, 2])

In [10]:
# 3维
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d,arr3d.shape

(array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]]]),
 (2, 2, 3))

In [11]:
arr3d[1,0] # 3维索引

array([7, 8, 9])

### 切片索引

In [12]:
# 向量
arr, arr[1:6]

(array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9]), array([ 1,  2,  3,  4, 12]))

In [13]:
# 矩阵
arr2d, arr2d[:2], arr2d[:2, :2], arr2d[:, :1]

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1, 2],
        [4, 5]]),
 array([[1],
        [4],
        [7]]))

In [17]:
# 先索引后切片
arr2d[1, :2], arr2d[1:2, :2]

(array([4, 5]), array([[4, 5]]))

In [16]:
# 先切片后索引
arr2d[:2, 1], arr2d[:2, 1:2]

(array([2, 5]),
 array([[2],
        [5]]))

### 布尔型索引