In [1]:
import numpy as np

# 第04章 NumPy基础：数组和矢量计算

## 4.1 NumPy的ndarray：一种多维数组对象

### 创建ndarray

In [2]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [3]:
np.zeros(3), np.zeros((2,3))

(array([0., 0., 0.]),
 array([[0., 0., 0.],
        [0., 0., 0.]]))

### ndarray的数据类型

### NumPy数组的运算

### 基本的索引和切片
切片是视图 <br/>
索引降维，切片不降维

In [4]:
# 列表 切片是新内存
a = list(range(10))
b = a[5:8]
b[:] = [10, 10, 10]
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
# 向量
arr = np.arange(10)
arr, arr[5], arr[5:8] # 索引 切片

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), 5, array([5, 6, 7]))

In [6]:
# 切片是视图 影响原对象
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [7]:
# 矩阵
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d, arr2d.shape

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 (3, 3))

In [8]:
arr2d[0][2], arr2d[0,2] # 索引

(3, 3)

In [9]:
arr2d[0,:2] # 切片

array([1, 2])

In [10]:
# 3维
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d,arr3d.shape

(array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]]]),
 (2, 2, 3))

In [11]:
arr3d[1,0] # 3维索引

array([7, 8, 9])

### 切片索引

In [12]:
# 向量
arr, arr[1:6]

(array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9]), array([ 1,  2,  3,  4, 12]))

In [13]:
# 矩阵
arr2d, arr2d[:2], arr2d[:2, :2], arr2d[:, :1]

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1, 2],
        [4, 5]]),
 array([[1],
        [4],
        [7]]))

In [14]:
# 先索引后切片
arr2d[1, :2], arr2d[1:2, :2]

(array([4, 5]), array([[4, 5]]))

In [15]:
# 先切片后索引
arr2d[:2, 1], arr2d[:2, 1:2]

(array([2, 5]),
 array([[2],
        [5]]))

### 布尔型索引
通过布尔索引切片获取的数组是创建了一个副本 <br/>
不能使用and和or，使用&和｜

In [16]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)

In [17]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [18]:
data[names == 'Bob'] # 切片

array([[-0.74709552,  1.02244131, -0.86470087, -1.27613059],
       [ 0.05541897,  0.14797066,  2.18251795,  0.52964654]])

In [19]:
data[names == 'Bob', 2:] # 切片 不降维

array([[-0.86470087, -1.27613059],
       [ 2.18251795,  0.52964654]])

In [20]:
data[names == 'Bob', 3] # 先切片后索引 不降维

array([-1.27613059,  0.52964654])

In [21]:
data.shape, data[names == 'Bob'].shape,data[names == 'Bob', 2:].shape,data[names == 'Bob', 3].shape

((7, 4), (2, 4), (2, 2), (2,))

### 花式索引

In [22]:
arr = np.empty((8,4))
for i in range(arr.shape[0]):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [23]:
# 不降维
arr[[4,3,0,6]], arr[[-3, -5, -7]]

(array([[4., 4., 4., 4.],
        [3., 3., 3., 3.],
        [0., 0., 0., 0.],
        [6., 6., 6., 6.]]),
 array([[5., 5., 5., 5.],
        [3., 3., 3., 3.],
        [1., 1., 1., 1.]]))

In [24]:
arr = np.arange(32).reshape((8, 4))
# 传多个列表会降维
arr, arr[[1, 5, 7, 2], [0, 3, 1, 2]]

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]]),
 array([ 4, 23, 29, 10]))

In [25]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

### 数组转置和轴对换
它返回的是源数据的视图（不会进行任何复制操作）

In [26]:
arr = np.arange(16).reshape((2, 2, 4))
arr,arr.T,arr.transpose((1, 0, 2)) # 坐标顺序按现在要求的排列

(array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7]],
 
        [[ 8,  9, 10, 11],
         [12, 13, 14, 15]]]),
 array([[[ 0,  8],
         [ 4, 12]],
 
        [[ 1,  9],
         [ 5, 13]],
 
        [[ 2, 10],
         [ 6, 14]],
 
        [[ 3, 11],
         [ 7, 15]]]),
 array([[[ 0,  1,  2,  3],
         [ 8,  9, 10, 11]],
 
        [[ 4,  5,  6,  7],
         [12, 13, 14, 15]]]))

In [27]:
arr.swapaxes(1, 2) # 只能两个轴对调

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

## 4.2 通用函数：快速的元素级数组函数
执行元素级运算的函数 <br/>
通过out参数在原数据上操作

In [28]:
# 一元
arr = np.arange(10)

In [29]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [30]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [31]:
# 二元
x = np.random.randn(8)
y = np.random.randn(8)
x,y

(array([-0.14245613,  0.72969798, -0.35995731, -0.45689739,  1.22835411,
        -0.64254822,  1.14375159, -0.63517402]),
 array([-0.91842998, -0.019659  , -0.41509625, -0.77446107, -0.53769319,
        -0.0921869 ,  0.35508434,  0.16609225]))

In [32]:
np.maximum(x, y) # 计算了x和y中元素级别最大的元素

array([-0.14245613,  0.72969798, -0.35995731, -0.45689739,  1.22835411,
       -0.0921869 ,  1.14375159,  0.16609225])

In [33]:
# 返回多个值
arr = np.random.randn(7) * 5
remainder, whole_part = np.modf(arr) # 分别获取小数部分和整数部分
arr, remainder, whole_part

(array([-4.391394  ,  2.85642084, -3.26195837,  7.72428548, -2.03194373,
         9.95461974,  4.08423246]),
 array([-0.391394  ,  0.85642084, -0.26195837,  0.72428548, -0.03194373,
         0.95461974,  0.08423246]),
 array([-4.,  2., -3.,  7., -2.,  9.,  4.]))

In [34]:
# 通过out参数 在原内存上操作
np.sqrt(arr,arr)

C:\Users\bing\AppData\Local\Temp\ipykernel_21160\851401715.py:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr,arr)


array([       nan, 1.69009492,        nan, 2.77925988,        nan,
       3.15509425, 2.02094841])

## 4.3 利用数组进行数据处理

In [35]:
# 网格坐标制作
points = np.arange(0, 3, 1)
xs, ys = np.meshgrid(points, points)
points, xs, ys

(array([0, 1, 2]),
 array([[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]),
 array([[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]]))

In [36]:
points = np.arange(-5, 5, 0.01)
xs, ys = np.meshgrid(points, points)
# points, xs, ys

In [37]:
z = np.sqrt(xs ** 2 + ys ** 2)
# %matplotlib inline
# import matplotlib.pyplot as plt

# plt.imshow(z, cmap=plt.cm.gray); plt.colorbar()
# plt.title("Image plot of $\sqrt{x^2 + y^2}$ for a grid of values")

### 将条件逻辑表述为数组运算
where通常用于根据另一个数组而产生一个新的数组

In [38]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

np.where(cond, xarr, yarr)

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [39]:
arr = np.random.randn(4, 4)
np.where(arr > 0, 2, arr)

array([[ 2.        , -0.35549041, -0.01789432,  2.        ],
       [-0.5532273 ,  2.        ,  2.        , -0.31353844],
       [-0.32427219, -0.34516449,  2.        ,  2.        ],
       [ 2.        ,  2.        ,  2.        ,  2.        ]])

### 数学和统计方法

In [40]:
arr = np.random.randn(5, 4)
arr

array([[ 1.48898645,  0.66387703,  1.27167704,  1.75996294],
       [ 0.89675155,  0.35901423, -0.89028208,  0.93841054],
       [ 1.16878252,  0.36923624,  0.8956543 ,  1.4180029 ],
       [ 1.3575341 ,  0.31094336, -0.36330349, -1.35303571],
       [ 0.72002522, -0.66260987,  0.10002801,  0.46079761]])

In [41]:
arr.mean(),np.mean(arr), arr.mean(axis=1)

(0.5455226453012891,
 0.5455226453012891,
 array([ 1.29612587,  0.32597356,  0.96291899, -0.01196543,  0.15456024]))

In [42]:
arr.sum(), arr.sum(axis=0)

(10.910452906025784, array([5.63207985, 1.04046099, 1.01377378, 3.22413829]))

In [43]:
# 向量累加
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28])

In [44]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr, arr.cumsum(),arr.cumsum(axis=0),arr.cumprod(axis=1)

(array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]),
 array([ 0,  1,  3,  6, 10, 15, 21, 28, 36]),
 array([[ 0,  1,  2],
        [ 3,  5,  7],
        [ 9, 12, 15]]),
 array([[  0,   0,   0],
        [  3,  12,  60],
        [  6,  42, 336]]))

### 用于布尔型数组的方法

In [45]:
arr = np.random.randn(100)
(arr > 0).sum()

50

In [46]:
bools = np.array([False, False, True, False])
bools.any(),bools.all()

(True, False)

### 排序
np.sort返回的是数组的已排序副本，而就地排序则会修改数组本身。

In [47]:
arr = np.random.randn(6)
arr.sort() # 本身排序
np.sort(arr) # 返回副本

array([-0.49879654,  0.01406013,  0.46181973,  1.10137011,  1.50008576,
        2.51915417])

In [48]:
# 5%的数
large_arr = np.random.randn(1000)
large_arr.sort()
large_arr[int(0.05*len(large_arr))]

-1.6749423555272869

### 唯一化以及其它的集合逻辑

In [49]:
# 去重且排序
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])

np.unique(names),np.unique(ints)

(array(['Bob', 'Joe', 'Will'], dtype='<U4'), array([1, 2, 3, 4]))

In [50]:
# 判断给的向量是否在给定向量里
values = np.array([6, 0, 0, 3, 2, 5, 6])
np.in1d(values, [2, 3, 6])

array([ True, False, False,  True,  True, False,  True])

## 4.4 用于数组的文件输入输出

In [51]:
arr = np.arange(10)
np.save('some_array', arr)

In [52]:
np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
np.savez('array_archive.npz', a=arr, b=arr)

In [54]:
arch = np.load('array_archive.npz')
arch['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
# 压缩
np.savez_compressed('arrays_compressed.npz', a=arr, b=arr)

## 4.5 线性代数
- dot

In [56]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(x, np.ones(3)), np.dot(x, np.ones(3).reshape(3,1)) # 矩阵向量计算

(array([ 6., 15.]),
 array([[ 6.],
        [15.]]))

In [57]:
from numpy.linalg import inv, qr

X = np.random.randn(5, 5) # 方阵
mat = X.T.dot(X)
mat.dot(inv(mat))

array([[ 1.00000000e+00, -1.69107151e-16,  7.44688017e-17,
         3.18544054e-16, -4.18494995e-17],
       [ 1.48309008e-16,  1.00000000e+00,  6.40137571e-16,
        -9.79414117e-16,  1.59830413e-17],
       [ 4.19006040e-16, -2.11622866e-15,  1.00000000e+00,
        -7.20671450e-16, -5.98209331e-17],
       [-4.78760528e-16, -4.69899758e-16, -5.33081033e-16,
         1.00000000e+00,  3.44396259e-18],
       [-2.84554675e-17, -9.94921474e-16,  1.32164583e-16,
         1.24492773e-17,  1.00000000e+00]])

In [60]:
q, r = qr(mat)
r,q # q是正交矩阵 q.T@q是单位阵  

(array([[-10.52381416,  -2.02041941,  -6.20419668,   7.24147159,
          -4.63371346],
        [  0.        ,  -4.40114112,  -5.26350533,   4.55730974,
           3.03382234],
        [  0.        ,   0.        ,  -3.6808865 ,  -3.34664293,
          -1.63058885],
        [  0.        ,   0.        ,   0.        ,  -0.39294772,
          -0.32119021],
        [  0.        ,   0.        ,   0.        ,   0.        ,
           4.35887699]]),
 array([[-0.80678612,  0.32124766,  0.00561056, -0.29852454, -0.39591377],
        [-0.02054294, -0.58167202,  0.06966531, -0.79247651,  0.16841429],
        [-0.31299671, -0.52265342, -0.72459275,  0.32000221, -0.03782054],
        [ 0.40667439,  0.43164053, -0.6644565 , -0.42186058, -0.16980462],
        [-0.29210125,  0.31460684, -0.1690508 , -0.04996308,  0.88579056]]))

In [62]:
q @ q.T

array([[ 1.00000000e+00, -1.07462273e-16, -6.88076390e-17,
         2.67586342e-18, -1.05958352e-16],
       [-1.07462273e-16,  1.00000000e+00,  9.69161867e-17,
        -8.87280561e-17, -4.51151763e-17],
       [-6.88076390e-17,  9.69161867e-17,  1.00000000e+00,
        -2.43253397e-17, -2.74355938e-17],
       [ 2.67586342e-18, -8.87280561e-17, -2.43253397e-17,
         1.00000000e+00,  5.98744148e-18],
       [-1.05958352e-16, -4.51151763e-17, -2.74355938e-17,
         5.98744148e-18,  1.00000000e+00]])

## 4.6 伪随机数生成

In [63]:
np.random.normal(size=(4, 4))

array([[-0.30251836, -0.42830216,  0.44733119,  0.36970843],
       [-0.67915831,  0.57366072, -1.27958367, -1.52046112],
       [ 1.29791637, -1.19803792,  0.02191936,  1.05010595],
       [-0.80737355, -0.19302599, -1.21503036, -0.24773108]])

In [66]:
np.random.randn(4,4)

array([[-0.65866002, -0.41574442,  1.3297811 , -0.0358048 ],
       [-1.33542638, -0.49580193,  1.51066037, -1.90518013],
       [-0.16263237,  2.04802132,  0.12282377,  0.09554887],
       [-0.59367381, -0.09067889,  0.5675584 , -1.09043716]])

In [67]:
np.random.seed(1234)

In [68]:
rng = np.random.RandomState(1234)
rng.randn(10)

array([ 0.47143516, -1.19097569,  1.43270697, -0.3126519 , -0.72058873,
        0.88716294,  0.85958841, -0.6365235 ,  0.01569637, -2.24268495])