In [1]:
import numpy as np

# 第04章 NumPy基础：数组和矢量计算

## 4.1 NumPy的ndarray：一种多维数组对象

### 创建ndarray

In [2]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [3]:
np.zeros(3), np.zeros((2,3))

(array([0., 0., 0.]),
 array([[0., 0., 0.],
        [0., 0., 0.]]))

### ndarray的数据类型

### NumPy数组的运算

### 基本的索引和切片
切片是视图 <br/>
索引降维，切片不降维

In [4]:
# 列表 切片是新内存
a = list(range(10))
b = a[5:8]
b[:] = [10, 10, 10]
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
# 向量
arr = np.arange(10)
arr, arr[5], arr[5:8] # 索引 切片

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), 5, array([5, 6, 7]))

In [6]:
# 切片是视图 影响原对象
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [7]:
# 矩阵
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d, arr2d.shape

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 (3, 3))

In [8]:
arr2d[0][2], arr2d[0,2] # 索引

(3, 3)

In [9]:
arr2d[0,:2] # 切片

array([1, 2])

In [10]:
# 3维
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d,arr3d.shape

(array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]]]),
 (2, 2, 3))

In [11]:
arr3d[1,0] # 3维索引

array([7, 8, 9])

### 切片索引

In [12]:
# 向量
arr, arr[1:6]

(array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9]), array([ 1,  2,  3,  4, 12]))

In [13]:
# 矩阵
arr2d, arr2d[:2], arr2d[:2, :2], arr2d[:, :1]

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1, 2],
        [4, 5]]),
 array([[1],
        [4],
        [7]]))

In [14]:
# 先索引后切片
arr2d[1, :2], arr2d[1:2, :2]

(array([4, 5]), array([[4, 5]]))

In [15]:
# 先切片后索引
arr2d[:2, 1], arr2d[:2, 1:2]

(array([2, 5]),
 array([[2],
        [5]]))

### 布尔型索引
通过布尔索引切片获取的数组是创建了一个副本 <br/>
不能使用and和or，使用&和｜

In [17]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)

In [18]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [24]:
data[names == 'Bob'] # 切片

array([[ 1.80678983,  0.8011866 , -0.01382817, -0.7549458 ],
       [ 0.56525111, -1.11986941,  1.10113066,  0.25304404]])

In [27]:
data[names == 'Bob', 2:] # 切片 不降维

array([[-0.01382817, -0.7549458 ],
       [ 1.10113066,  0.25304404]])

In [30]:
data[names == 'Bob', 3] # 先切片后索引 不降维

array([-0.7549458 ,  0.25304404])

In [31]:
data.shape, data[names == 'Bob'].shape,data[names == 'Bob', 2:].shape,data[names == 'Bob', 3].shape

((7, 4), (2, 4), (2, 2), (2,))

### 花式索引

In [36]:
arr = np.empty((8,4))
for i in range(arr.shape[0]):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [44]:
# 不降维
arr[[4,3,0,6]], arr[[-3, -5, -7]]

(array([[16, 17, 18, 19],
        [12, 13, 14, 15],
        [ 0,  1,  2,  3],
        [24, 25, 26, 27]]),
 array([[20, 21, 22, 23],
        [12, 13, 14, 15],
        [ 4,  5,  6,  7]]))

In [45]:
arr = np.arange(32).reshape((8, 4))
# 传多个列表会降维
arr, arr[[1, 5, 7, 2], [0, 3, 1, 2]]

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]]),
 array([ 4, 23, 29, 10]))

In [46]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

### 数组转置和轴对换